repos:
  - repo: local
    hooks:
      - id: fmt-rust
        name: check rust format
        entry: cargo fmt --all
        language: system
        pass_filenames: false
      - id: clippy-rust
        name: run rust clippy
        entry: |
          cargo clippy --all-features --fix
          cargo clippy --all-features -- -D warnings
        language: system
        pass_filenames: false